# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ada1127e62b4b21cbcd1ab6f04551703ca6bda131cf4b5b98533533643ec553b272dfe4293f10e22007d0a72692e34b32f9b7c702aa2b78d14a86da6377bf2a6

test:
  secret_key_base: 741ec48c66ac9d105a1ea6379779ba0314958196acc606ae5b4da9439777f6215eda38c102b95d5a1fc4dd58c05c4017af0de887d4a6fd78a1d58475d355f6ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
